name: linting

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Setup Go 19.1
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'

      - name: Run Linting on Code Base
        uses: github/super-linter/slim@v4.9.4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_GO: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          # To disable unused feature from Super linter
          GITHUB_TOKEN: InvalidToken
    