name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Build package
        run: make build

      - name: Run unit tests
        run: make test

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    services:
      my-postgres-container:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
